[package]
authors = ["Oliver Cooper <oliver.cooper@me.com>"]
edition = "2021"
name = "mqtt-garage"
version = "0.1.0"

[dependencies]
chrono = "0.4"
chrono-tz = "0.8"
log = "0.4"
rppal = {version = "0.11.3", optional = true}
rumqttc = "0.12.0"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1"
serde_with = "1.6.4"
simple_logger = "4.3.3"
thiserror = "1.0.58"
tokio = {version = "1.37", features = ["full"]}
toml = "0.5.8"

[features]
arm = ["rppal"]
