[package]
authors = ["Oliver Cooper <oliver.cooper@me.com>"]
edition = "2018"
name = "mqtt-garage"
version = "0.1.0"

[dependencies]
toml = "0.5.8"
serde = { version = "1.0", features = ["derive"] }
serde_with = "1.6.4"
rppal = { version = "0.11.3", optional = true }
rumqttc = "0.12.0"
tokio = { version = "1", features = ["full"] }
async-trait = "0.1.48"
log = "0.4"
simple_logger = "1.11.0"
chrono = "0.4"
chrono-tz = "0.8"

[features]
arm = ["rppal"]