[package]
authors = ["Oliver Cooper <oliver.cooper@me.com>"]
edition = "2018"
name = "mqtt-garage"
version = "0.1.0"

[dependencies]
toml = "0.5.8"
serde = { version = "1.0", features = ["derive"] }
serde_with = "1.6.4"
rppal = { version = "0.11.3", optional = true }
rumqttc = "0.5.0"
tokio = "1.4"
async-trait = "0.1.48"
futures = "0.3"

[features]
arm = ["rppal"]